import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header"


const roboto = Roboto({
  subsets: ["latin"],
  weight: ['200']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={roboto.className}>
      <html>
        <body>
        <Header />
        {children}
        </body>
      </html>
      
    </main>
        
     
  );
}
